const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('bazar', {
  runtime: {
    platform: process.platform,
  },
  db: {
    getProducts: (filters) => ipcRenderer.invoke('db:getProducts', filters),
    checkRequiredTagsForProduct: (map) => ipcRenderer.invoke('db:checkRequiredTagsForProduct', map),
    addProduct: (product) => ipcRenderer.invoke('db:addProduct', product),
    updateProduct: (product) => ipcRenderer.invoke('db:updateProduct', product),
    deleteProduct: (id) => ipcRenderer.invoke('db:deleteProduct', id),
    searchProducts: (query) => ipcRenderer.invoke('db:searchProducts', query),
    nextCodigoMsr: () => ipcRenderer.invoke('db:nextCodigoMsr'),
    getMonserratDbPath: () => ipcRenderer.invoke('db:getMonserratDbPath'),
    resetToFactorySeed: () => ipcRenderer.invoke('db:resetToFactorySeed'),
    getTagGroupsForProduct: () => ipcRenderer.invoke('db:getTagGroupsForProduct'),
    getProductById: (id) => ipcRenderer.invoke('db:getProductById', id),
    getProductByCodigo: (codigo) => ipcRenderer.invoke('db:getProductByCodigo', codigo),
    getInventoryList: (filters) => ipcRenderer.invoke('db:getInventoryList', filters),
    getTagLabelsForMap: (map) => ipcRenderer.invoke('db:getTagLabelsForMap', map),
    suggestNombreFromTags: (payload) => ipcRenderer.invoke('db:suggestNombreFromTags', payload),
    getNombreEtiquetaDesdeTags: (payload) => ipcRenderer.invoke('db:getNombreEtiquetaDesdeTags', payload),
    suggestPrecioFromTags: (payload) => ipcRenderer.invoke('db:suggestPrecioFromTags', payload),
    getReferenceRows: (payload) => ipcRenderer.invoke('db:getReferenceRows', payload),
    getReferenceSnapshot: (payload) => ipcRenderer.invoke('db:getReferenceSnapshot', payload),
    getSales: (filters) => ipcRenderer.invoke('db:getSales', filters),
    addSale: (sale) => ipcRenderer.invoke('db:addSale', sale),
    getCredits: (filters) => ipcRenderer.invoke('db:getCredits', filters),
    listClientes: () => ipcRenderer.invoke('db:listClientes'),
    addCliente: (payload) => ipcRenderer.invoke('db:addCliente', payload),
    updateCliente: (payload) => ipcRenderer.invoke('db:updateCliente', payload),
    addCreditoMovimiento: (payload) => ipcRenderer.invoke('db:addCreditoMovimiento', payload),
    getCreditoMovimientos: (payload) => ipcRenderer.invoke('db:getCreditoMovimientos', payload),
    suggestByTags: (tags) => ipcRenderer.invoke('db:suggestByTags', tags),
    getWelcomeSnapshot: () => ipcRenderer.invoke('db:getWelcomeSnapshot'),
    getBanquetaSidebarSnapshot: () => ipcRenderer.invoke('db:getBanquetaSidebarSnapshot'),
    listBanquetaSalidas: () => ipcRenderer.invoke('db:listBanquetaSalidas'),
    getActiveBanquetaSalida: () => ipcRenderer.invoke('db:getActiveBanquetaSalida'),
    createBanquetaSalida: (payload) => ipcRenderer.invoke('db:createBanquetaSalida', payload),
    updateBanquetaSalida: (payload) => ipcRenderer.invoke('db:updateBanquetaSalida', payload),
    getBanquetaSalidaDetail: (id) => ipcRenderer.invoke('db:getBanquetaSalidaDetail', id),
    addProductToBanquetaSalida: (payload) => ipcRenderer.invoke('db:addProductToBanquetaSalida', payload),
    removeBanquetaSalidaItem: (itemId) => ipcRenderer.invoke('db:removeBanquetaSalidaItem', itemId),
    setBanquetaSalidaItemResult: (payload) => ipcRenderer.invoke('db:setBanquetaSalidaItemResult', payload),
    activateBanquetaSalida: (id) => ipcRenderer.invoke('db:activateBanquetaSalida', id),
    closeBanquetaSalida: (id) => ipcRenderer.invoke('db:closeBanquetaSalida', id),
    deleteBanquetaSalida: (id) => ipcRenderer.invoke('db:deleteBanquetaSalida', id),
    reorderBanquetaSalidaItems: (payload) => ipcRenderer.invoke('db:reorderBanquetaSalidaItems', payload),
    removeBanquetaSalidaItemsBulk: (itemIds) => ipcRenderer.invoke('db:removeBanquetaSalidaItemsBulk', itemIds),
    previewPriceAdjust: (payload) => ipcRenderer.invoke('db:previewPriceAdjust', payload),
    applyPriceAdjust: (payload) => ipcRenderer.invoke('db:applyPriceAdjust', payload),
    getReferencePatternStats: (payload) => ipcRenderer.invoke('db:getReferencePatternStats', payload),
    getCuadernoTagGroups: () => ipcRenderer.invoke('db:getCuadernoTagGroups'),
    getTagCatalogForManager: () => ipcRenderer.invoke('db:getTagCatalogForManager'),
    cuadernoRenameTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoRenameTagGroup', payload),
    cuadernoDeleteTagOption: (payload) => ipcRenderer.invoke('db:cuadernoDeleteTagOption', payload),
    cuadernoDeleteTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoDeleteTagGroup', payload),
    listPriceRulesAdmin: () => ipcRenderer.invoke('db:listPriceRulesAdmin'),
    cuadernoAddTagGroup: (payload) => ipcRenderer.invoke('db:cuadernoAddTagGroup', payload),
    cuadernoAddTagOption: (payload) => ipcRenderer.invoke('db:cuadernoAddTagOption', payload),
    cuadernoMoveTagOption: (payload) => ipcRenderer.invoke('db:cuadernoMoveTagOption', payload),
    cuadernoRenameTagOption: (payload) => ipcRenderer.invoke('db:cuadernoRenameTagOption', payload),
    cuadernoSetTagOptionActive: (payload) => ipcRenderer.invoke('db:cuadernoSetTagOptionActive', payload),
    cuadernoSetTagGroupStyle: (payload) => ipcRenderer.invoke('db:cuadernoSetTagGroupStyle', payload),
    cuadernoSetTagOptionStyle: (payload) => ipcRenderer.invoke('db:cuadernoSetTagOptionStyle', payload),
    cuadernoReorderTagGroups: (payload) => ipcRenderer.invoke('db:cuadernoReorderTagGroups', payload),
    cuadernoUpsertPriceRule: (payload) => ipcRenderer.invoke('db:cuadernoUpsertPriceRule', payload),
    cuadernoDeletePriceRule: (payload) => ipcRenderer.invoke('db:cuadernoDeletePriceRule', payload),
    listTagPriceRulesSummary: () => ipcRenderer.invoke('db:listTagPriceRulesSummary'),
    listTagPriceRulesForCuaderno: () => ipcRenderer.invoke('db:listTagPriceRulesForCuaderno'),
    setTagOptionPriceRule: (payload) => ipcRenderer.invoke('db:setTagOptionPriceRule', payload),
    getPriceCombosForAnchor: (payload) => ipcRenderer.invoke('db:getPriceCombosForAnchor', payload),
    replacePriceCombosForAnchor: (payload) => ipcRenderer.invoke('db:replacePriceCombosForAnchor', payload),
    listInvPricingRules: () => ipcRenderer.invoke('db:listInvPricingRules'),
    getInvPricingRule: (payload) => ipcRenderer.invoke('db:getInvPricingRule', payload),
    upsertInvPricingRule: (payload) => ipcRenderer.invoke('db:upsertInvPricingRule', payload),
    deleteInvPricingRule: (payload) => ipcRenderer.invoke('db:deleteInvPricingRule', payload),
  },
  settings: {
    get: () => ipcRenderer.invoke('settings:get'),
    set: (patch) => ipcRenderer.invoke('settings:set', patch),
    pickLabelPdfFolder: () => ipcRenderer.invoke('settings:pickLabelPdfFolder'),
  },
  printers: {
    list: () => ipcRenderer.invoke('printers:list'),
    diagnostic: () => ipcRenderer.invoke('printers:diagnostic'),
    testPrint: (printerName) => ipcRenderer.invoke('printers:testPrint', { printerName }),
    printLabel: (payload) => ipcRenderer.invoke('printers:printLabel', payload),
  },
  banqueta: {
    printSheet: (detail) => ipcRenderer.invoke('banqueta:printSheet', { detail }),
  },
  labels: {
    list: () => ipcRenderer.invoke('labels:list'),
    getActive: () => ipcRenderer.invoke('labels:getActive'),
    upsert: (template) => ipcRenderer.invoke('labels:upsert', template),
    remove: (id) => ipcRenderer.invoke('labels:remove', id),
    setActive: (id) => ipcRenderer.invoke('labels:setActive', id),
    duplicate: (id) => ipcRenderer.invoke('labels:duplicate', id),
    restoreDefault: () => ipcRenderer.invoke('labels:restoreDefault'),
  },
  productImage: {
    pick: () => ipcRenderer.invoke('productImage:pick'),
  },
  tagIconImage: {
    pick: () => ipcRenderer.invoke('tagIconImage:pick'),
  },
  devices: {
    open: () => ipcRenderer.invoke('devices:open'),
  },
  rive: {
    open: () => ipcRenderer.invoke('rive:open'),
  },
  pdv: {
    open: () => ipcRenderer.invoke('pdv:open'),
  },
  window: {
    isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
    minimize: () => ipcRenderer.invoke('window:minimize'),
    toggleMaximize: () => ipcRenderer.invoke('window:maximizeToggle'),
    close: () => ipcRenderer.invoke('window:close'),
    setWelcomeMode: (compact) => ipcRenderer.invoke('window:setWelcomeMode', Boolean(compact)),
    onState: (callback) => {
      const handler = (_event, state) => {
        if (typeof callback === 'function') callback(state)
      }
      ipcRenderer.on('window:state', handler)
      return () => ipcRenderer.removeListener('window:state', handler)
    },
  },
})
